In [57]:
from datasets import load_dataset
dataUK = load_dataset("BramVanroy/conll2003")
LabeltoID_UK = {
    'O': 0,
    'B-PER': 1,
    'I-PER': 2,
    'B-ORG': 3,
    'I-ORG': 4,
    'B-LOC': 5,
    'I-LOC': 6,
    'B-MISC': 7,
    'I-MISC': 8
}
IDtoLabel_UK = {
    0: 'O',
    1: 'B-Person',
    2: 'I-Person',
    3: 'B-Organization',
    4: 'I-Organization',
    5: 'B-Location',
    6: 'I-Location',
    7: 'B-Misc',
    8: 'I-Misc'
}

dataUS = load_dataset("hgissbkh/ontonotes5")
#NOTE: Time merged into Date, change if necessary
IDtoLabel_US = {
    0:'O',
    1:'B-Misc',
    2:'B-Date',
    3:'I-Date',
    4:'B-Person',
    5:'I-Person',
    6:'B-NORP',
    7:'B-Misc',
    8:'I-Misc',
    9:'B-Misc',
    10:'I-Misc',
    11:'B-Organization',
    12:'I-Organization',
    13:'B-Misc',
    14:'I-Misc',
    15:'B-Misc',
    16:'B-Money',
    17:'I-Money',
    18:'B-Misc',
    19:'I-Misc',
    20:'B-Facility',
    21:'B-Date',
    22:'I-Misc',
    23:'B-Location',
    24:'B-Misc',
    25:'I-Misc',
    26:'I-NORP',
    27:'I-Location',
    28:'B-Product',
    29:'I-Date',
    30:'B-Misc',
    31:'I-Misc',
    32:'I-Facility',
    33:'B-Misc',
    34:'I-Product',
    35:'I-Misc',
    36:'I-Misc'
}
LabeltoID_US = {
    "O": 0,
    "B-CARDINAL": 1,
    "B-DATE": 2,
    "I-DATE": 3,
    "B-PERSON": 4,
    "I-PERSON": 5,
    "B-NORP": 6,
    "B-GPE": 7,
    "I-GPE": 8,
    "B-LAW": 9,
    "I-LAW": 10,
    "B-ORG": 11,
    "I-ORG": 12, 
    "B-PERCENT": 13,
    "I-PERCENT": 14, 
    "B-ORDINAL": 15, 
    "B-MONEY": 16, 
    "I-MONEY": 17, 
    "B-WORK_OF_ART": 18, 
    "I-WORK_OF_ART": 19, 
    "B-FAC": 20, 
    "B-TIME": 21, 
    "I-CARDINAL": 22, 
    "B-LOC": 23, 
    "B-QUANTITY": 24, 
    "I-QUANTITY": 25, 
    "I-NORP": 26, 
    "I-LOC": 27, 
    "B-PRODUCT": 28, 
    "I-TIME": 29, 
    "B-EVENT": 30,
    "I-EVENT": 31,
    "I-FAC": 32,
    "B-LANGUAGE": 33,
    "I-PRODUCT": 34,
    "I-ORDINAL": 35,
    "I-LANGUAGE": 36
}
LabelToID = {
    'O': 0,
    'B-Date': 1,
    'I-Date': 2,
    'B-Person': 3,
    'I-Person': 4,
    'B-Location': 5,
    'I-Location': 6,
    'B-Facility': 7,
    'I-Facility': 8,
    'B-Organization': 9,
    'I-Organization': 10,
    'B-Misc': 11,
    'I-Misc': 12,
    'B-Money': 13,
    'I-Money': 14,
    'B-NORP': 15,
    'I-NORP': 16,
    'B-Product': 17,
    'I-Product': 18}

In [58]:
trainDataUK=dataUK['train'].to_pandas()
trainDataUK['ner_tags'] = trainDataUK['ner_tags'].apply(lambda x: [IDtoLabel_US[i] for i in x])
trainDataUK['ner_tags'] = trainDataUK['ner_tags'].apply(lambda x: [LabelToID[i] for i in x])
trainDataUK.drop(columns=['id','pos_tags','chunk_tags'],inplace=True)
trainDataUK

,tokens,ner_tags
0,"[EU, rejects, German, call, to, boycott, Briti...","[2, 0, 11, 0, 0, 0, 11, 0, 0]"
1,"[Peter, Blackburn]","[11, 1]"
2,"[BRUSSELS, 1996-08-22]","[4, 0]"
3,"[The, European, Commission, said, on, Thursday...","[0, 2, 3, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0,..."
4,"[Germany, 's, representative, to, the, Europea...","[4, 0, 0, 0, 0, 2, 3, 0, 0, 0, 11, 1, 0, 0, 0,..."
...,...,...
14036,"[on, Friday, :]","[0, 0, 0]"
14037,"[Division, two]","[0, 0]"
14038,"[Plymouth, 2, Preston, 1]","[2, 0, 2, 0]"
14039,"[Division, three]","[0, 0]"
14040,"[Swansea, 1, Lincoln, 2]","[2, 0, 2, 0]"

In [59]:
trainDataUS=dataUS['train'].to_pandas()
trainDataUS['ner_tags'] = trainDataUS['tags'].apply(lambda x: [IDtoLabel_US[i] for i in x])
trainDataUS['ner_tags'] = trainDataUS['ner_tags'].apply(lambda x: [LabelToID[i] for i in x])
trainDataUS.drop(columns='tags',inplace=True)
trainDataUS

,tokens,ner_tags
0,"[People, start, their, own, businesses, for, m...","[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,"[But, a, chance, to, fill, out, sales, -, tax,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0]"
2,"[Red, tape, is, the, bugaboo, of, small, busin...","[0, 0, 0, 0, 0, 0, 0, 0, 0]"
3,"[Ironically, ,, the, person, who, wants, to, r...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,"[Yet, every, business, owner, has, to, face, t...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...
59919,"[Probably, .]","[0, 0]"
59920,"[Why, ?]","[0, 0]"
59921,"[I, do, n't, think, they, can]","[0, 0, 0, 0, 0, 0]"
59922,"[but, I, think, they, 'll, try, .]","[0, 0, 0, 0, 0, 0, 0]"
59923,"[You, know, how, people, are, .]","[0, 0, 0, 0, 0, 0]"

In [60]:
import random
import pandas as pd
from tqdm import tqdm
def sentencesWithTag(df:pd.DataFrame,tag:int):
    '''Takes dataframe and ID of tag, returns list of DF indexes of sentences that include the tag\\
    Helper function :)'''
    sentences=[]
    for i,x in enumerate(df):
        if tag in x:sentences.append(i)
    return sentences

def switchTokensDepr(df1:pd.DataFrame,df2:pd.DataFrame,n:int):
    '''Takes dataframe and number of switches. Switches tokens with same NER tag n amount of times'''
    for i in tqdm(range(n)):
        tag=random.randint(1,18) # Choose a tag
        s1=sentencesWithTag(df1['ner_tags'],tag) # Find all sentences with tag
        s2=sentencesWithTag(df2['ner_tags'],tag)
        s1=random.choices(s1) # Randomly choose 2 sentences with same tag

        tokens1 = list(df1.at[s1, 'tokens'])
        tokens2 = list(df2.at[s2, 'tokens'])
        tags1   = df1.at[s1, 'ner_tags']
        tags2   = df2.at[s2, 'ner_tags'] # Get rows of sentences
        # print(r1)
        # print(r2)
        # print('Tag:',tag)
        # print()
        indices1 = [i for i, x in enumerate(tags1) if x == tag]
        indices2 = [i for i, x in enumerate(tags2) if x == tag]
        # print(indices1)
        # print(indices2)
        # print()
        indice1=random.choice(indices1)
        indice2=random.choice(indices2)
        tokens1[indice1], tokens2[indice2] = tokens2[indice2], tokens1[indice1]
        #print(tokens2[indice2],tokens1[indice2])
        df1.at[s1, 'tokens'] = tokens1
        df2.at[s2, 'tokens'] = tokens2
    return df1, df2

In [ ]:
def switchTokens(df1: pd.DataFrame, df2: pd.DataFrame, n: int):
    '''Take 2 dataframes, switches tokens with the same NER tag n amount of times between them'''
    df1 = df1.copy()
    df2 = df2.copy()
    all_tags = set(tag for tags in df1['ner_tags'] for tag in tags if tag != 0)

    for _ in tqdm(range(n)):
        tag = random.choice(list(all_tags))

        s1 = sentencesWithTag(df1['ner_tags'], tag) # All rows including tag
        s2 = sentencesWithTag(df2['ner_tags'], tag)

        if len(s1) < 1 or len(s2) < 1: # If less than 1 row, skip
            continue

        s1 = random.choice(s1)  # Get index of 1 random row
        s2 = random.choice(s2)

        tokens1 = list(df1.at[s1, 'tokens']) # Tokens of said row
        tokens2 = list(df2.at[s2, 'tokens'])

        tags1   = df1.at[s1, 'ner_tags'] # Tags of said row
        tags2   = df2.at[s2, 'ner_tags']

        idx1 = random.choice([i for i, t in enumerate(tags1) if t == tag]) # If multiple words with same tag, choose one
        idx2 = random.choice([i for i, t in enumerate(tags2) if t == tag])

        tokens1[idx1], tokens2[idx2] = tokens2[idx2], tokens1[idx1]  # Swap between the 2 sentences

        df1.at[s1, 'tokens'] = tokens1
        df2.at[s2, 'tokens'] = tokens2

    return df1, df2

In [62]:
switchedDf1,switchedDf2=switchTokens(trainDataUS,trainDataUK,100)

100%|██████████| 100/100 [00:05<00:00, 18.13it/s]

In [63]:
changed_rows = []
for idx in trainDataUS.index:
    if list(trainDataUS.at[idx, 'tokens']) != list(switchedDf1.at[idx, 'tokens']):
        changed_rows.append(idx)

print(f"{len(changed_rows)} rows changed out of {len(trainDataUS)}")

changed_rows = []
for idx in trainDataUK.index:
    if list(trainDataUK.at[idx, 'tokens']) != list(switchedDf2.at[idx, 'tokens']):
        changed_rows.append(idx)

print(f"{len(changed_rows)} rows changed out of {len(trainDataUK)}")

41 rows changed out of 59924
41 rows changed out of 14041